export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const FETCH_INGRDIENTS_FAILED = 'FETCH_INGRDIENTS_FAILED';
export const SET_INGRDIENTS = 'SET_INGRDIENTS';

export const BURGER_PURCHASE_SUCCESS = 'BURGER_PURCHASE_SUCCESS';
export const BURGER_PURCHASE_FAIL = 'BURGER_PURCHASE_FAIL';
export const BURGER_PURCHASE_START= 'BURGER_PURCHASE_START';
export const BURGER_PURCHASE= 'BURGER_PURCHASE';
export const PURCHASED_INIT = 'PURCHASED_INIT';

export const FETCHED_ORDER_SUCCESS = 'FETCHED_ORDER_SUCCESS';
export const FETCHED_ORDER_FAIL = 'FETCHED_ORDER_FAIL';
export const FETCHED_ORDER_START= 'FETCHED_ORDER_START';
export const FETCHED_ORDER= 'FETCHED_ORDER';

export const ONLOGGEDIN = 'ONLOGGEDIN';
export const ONLOGGEDOUT = 'ONLOGGEDOUT';
export const ONEMAIL = 'ONEMAIL';
export const ONPASSWORD = 'ONPASSWORD';


export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_START= 'AUTH_START';
export const AUTH_SUCCESS= 'AUTH_SUCCESS';

export const ALBUM_FAIL = 'ALBUM_FAIL';
export const ALBUM_START= 'ALBUM_START';
export const ALBUM_SUCCESS= 'ALBUM_SUCCESS';
export const INSIDEALBUM_SUCCESS = 'INSIDEALBUM_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const ONVIEW_ALBUM = 'ONVIEW_ALBUM';
export const AUTH_SUCCESSLOAD = 'AUTH_SUCCESSLOAD';
export const AUTH_REDIRECT_PATH = 'AUTH_REDIRECT_PATH';




