

export const ONLOGGEDIN = 'ONLOGGEDIN';
export const ONLOGGEDOUT = 'ONLOGGEDOUT';
;


export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_START= 'AUTH_START';
export const AUTH_SUCCESS= 'AUTH_SUCCESS';

export const ALBUM_FAIL = 'ALBUM_FAIL';
export const ALBUM_START= 'ALBUM_START';
export const ALBUM_SUCCESS= 'ALBUM_SUCCESS';
export const INSIDEALBUM_SUCCESS = 'INSIDEALBUM_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const ONVIEW_ALBUM = 'ONVIEW_ALBUM';
export const AUTH_SUCCESSLOAD = 'AUTH_SUCCESSLOAD';
export const AUTH_REDIRECT_PATH = 'AUTH_REDIRECT_PATH';




